### ISSUE TITLE
Allow Optional Fields in BankModel

### ISSUE THREAD

**Issue by hemanth-sunkireddy** [IMS-IIITH/backend#6]
bank_model_format = {
  rollNumber: null,
  selectBank: null,
  accountHolderName: null,
  accountNumber: null,
  bankName: null,
  branchName: null,
  ifscCode: null,
  bankAddress: null,
  remarks: null,
  base64Data: null,
};

#5 in this pull request, I didn't add optional to this fields: 
1. bankName,
2.  branchName,
3.  ifscCode,
4.  bankAddress and 
5. remarks
By default frontend is sending null but backend is expecting to be string. add optional to this 5 fields, so these 5 keys have either string or null in data.

**Comment by bhavberi** [comment]
Made those fields Optional.
